# Generated by Django 4.2.6 on 2023-10-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsectCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateTimeField()),
                ('insect_quantity', models.IntegerField()),
                ('insect_area', models.FloatField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('trap_id', models.IntegerField()),
            ],
        ),
    ]
